### ISSUE TITLE
Problem to edit memory layer

### ISSUE THREAD

**Issue by GlaDal** [ccrook/QGIS-MemoryLayerSaver-Plugin#3]
Hi, 

I'm not that will be useful to write you without an error message. But sometimes after having created a memory layer (with EasyCustomLabelling) and after having save this layer with memory layer saver, I have problems for editing them when I reopen the project. I can move my label but the line between the object and the label doesn't follow my label.
Is there any solution.

Thank you for your contribution !

Bye

Gladal

**Comment by ccrook** [comment]
stale issue!
