### ISSUE TITLE
Hide memory layer saving dialogue

### ISSUE THREAD

**Issue by fuzzysolutions** [ccrook/QGIS-MemoryLayerSaver-Plugin#7]
QGIS 3.2 shows a reminder that memory layers will be lost when attempting to close a project containing such layers:
![grafik](https://user-images.githubusercontent.com/29453443/45208776-b9ab2700-b28b-11e8-8f51-f8809687786f.png)
As MemoryLayerSaver takes care of saving memory layers, there is no need for this query as long as the plugin is activated. It would be a nice feature if the plugin could hide the query.

**Comment by ccrook** [comment]
@fuzzysolutions  Thanks for raising this.  I've asked on the developer list and Mathieu has responded with what I need to do

> There is:
>
> QgsSettings().value( QStringLiteral( "askToSaveMemoryLayers" ), true, QgsSettings::App )
>
> Switch that to false, that'll disable the warning.

I'll look at putting that in shortly.
